[package]
name = "vitre-client"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
serde_json.workspace = true
tokio.workspace = true
vitre-contracts.workspace = true
vitre-rpc.workspace = true
vitre-sidecar.workspace = true
vitre-state.workspace = true

[dev-dependencies]
anyhow.workspace = true

[[example]]
name = "spike_client"
